### ISSUE TITLE
not updated

### ISSUE THREAD

**Issue by lc-thomas** [azakhi/azakhi.github.io#1]
Hello !

Great tool, one thing though, it doesn't seem to be updated.
There were a few changes in 3.9.1 : https://pop3.fandom.com/wiki/Character_Creation

**Comment by azakhi** [comment]
Hey @K-marad,
Thanks for creating an issue! I wasn't aware of an update. I have updated the tool and also checked it twice myself but I would still appreciate it if you can also check it. Thanks!

**Comment by lc-thomas** [comment]
Oh thank you ! <3
