### ISSUE TITLE
Wrong result for PoP character creator

### ISSUE THREAD

**Issue by AujaWindur** [azakhi/azakhi.github.io#2]
The 4th stage choice "A series of unfortunate events" have the wrong values for when the 3rd stage choice is either "An engineer and builder", or "A huntsman and tracker".

"An engineer and builder" should give a bonus of +2 to engineering, but it only gives the base skill bonuses from "A series of unfortunate events"
"A huntsman and tracker" gets a +2 bonus to engineering on top of the correct bonus of +1 riding and +1 pathfinding that the choice is supposed to give.

**Comment by azakhi** [comment]
Thanks for reporting. I ll check if there is any other problems with the latest update.
