### ISSUE TITLE
"Banner" does not revert to 'No'

### ISSUE THREAD

**Issue by bonnertech** [azakhi/azakhi.github.io#4]
If you choose any start option that provides your own banner, then the "Banner" field changes to Yes.

After this point, if you choose a new start option that does NOT provide a banner, the field does not reset to "No."

**Comment by azakhi** [comment]
Thanks for reporting @bonnertech , upon testing briefly I didn't see a problem. It reset back to no (except for -please select one- option). Could you please provide a specific example? I will also test more thoroughly once I have time.

**Comment by Zhuikin** [comment]
I believe the issue to be slightly different.

The option father was "A retired Adventurer" displays "YES" while it should be "NO" (Just double checked running 3.9.4, hotfix 3 DLed from Nexus).
(Being just after father was "A former Knight" is might seem, like it didn't revert properly...)

**Comment by azakhi** [comment]
@Zhuikin thanks for pointing that out. I will fix it right after I get back home.
